### PR TITLE
chore: bump version 0.2.0 => 0.2.1

### PR DESCRIPTION
**Pull request by lgpage**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by lgpage** [comment]
@conda-forge-admin, please rerender

**Comment by lgpage** [comment]
Hi @jonashaag, please can you review this when you get a gap? Thank you.

**Comment by jonashaag** [comment]
You might want to add yourself to the maintainers

**Comment by lgpage** [comment]
@jonashaag will do. Do you know if adding myself to the `meta.yaml` is sufficient?

**Comment by jonashaag** [comment]
Yes

**Pull request merged**
